name: Invitation to the Recode-Hive GitHub Community Organization
description: I would like to be part of this awesome community
body:
  - type: input
    id: name
    attributes:
      label: Name
      placeholder: Insert your name here
  - type: markdown
    attributes:
      value: |
       
        <b>For getting invited to the Recode-Hive Community click [here](https://github.com/Recode-Hive/)</b>
