name: Invitation to the Recode-Hive GitHub Community Organization
body:
  - type: input
    id: name
    attributes:
      label: Name
      placeholder: Insert your name here
  - type: markdown
    attributes:
      value: |
        For getting invited to the Recode-Hive Community [here](https://github.com/Recode-Hive/)
